apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onboarding-bot-staging
bases:
- ./kservice.yaml
images:
- name: devlaunchers/onboardingbot
  newName: devlaunchers/onboardingbot
  newTag: fcb242d-202312142130 # {"$imagepolicy": "onboarding-bot-staging:onboarding-bot:tag"}
